### ISSUE TITLE
Resposne with WWW-Authenticate header when no token provided

### ISSUE THREAD

**Issue by travisspencer** [curityio/nginx_introspect#11]
According to RFC 6750, we need to respond with a `WWW-Authenticate` header when no token is presented to the gateway.

**Comment by anestos** [comment]
Should that be in the response for an invalid access token too?

**Comment by travisspencer** [comment]
I have to read the spec more carefully, but IIRC a an invalid token should
have a www header but with different values, error values. If so, I'll add
this at the same time.
